sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.6.0

# this isn't necessary, but otherwise Travis loads Ruby to start with, which is confusing
language: generic

before_install:
  - sudo apt-get update
  - sudo apt-get install -q -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

after_success:
  - docker-compose run web codecov

script:
  - docker-compose run web py.test --cov=. --ds=principal_travel.settings.test
